project_id = "GestaoNexus"

[functions.generate-weekly-tasks]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.places-search]
verify_jwt = false

[functions.places-details]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
